[package]
name = "beenet-artifact"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Protocol-level Beenet Wasm packaging and inspection."

[dependencies]
anyhow.workspace = true
beenet-common.workspace = true
serde.workspace = true
toml.workspace = true
wasmparser.workspace = true
