[package]
name = "beenet-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Pack and inspect Beenet tasks."

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
beenet-common = { workspace = true }
beenet-manifest = { workspace = true }
