[package]
name = "beenet-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Wire types for Gateway ↔ Worker libp2p protocol."

[dependencies]
beenet-common = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
